# Site settings
title: "Open Data Policy Hub"
description: "Learn how to write your own open data policy, and see existing ones."
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
# url: "https://18f.gsa.gov" # the base hostname & protocol for your sites
# federalist_url: "https://federalist.18f.gov"
localhost: "localhost:4000"
env: "production"
logo: /assets/img/logos/sunlight-logo-dark.png
tag_dir: tags
github_repo: https://github.com/sunlightpolicy/open-data-policy-hub/blob/master

related_posts: 3

google_analytics: 'UA-48789618-10'

# blog archive at /blog
paginate: 5
paginate_path: "blog/page/:num"

jekyll-archives:
  enabled:
    - 'tags'
  layout: tag-results
  permalinks:
    tag: '/tags/:name/'

collections:
  policies:
    output: true
    permalink: /collection/:path/
  states:
    output: true
    permalink: /state/:path/
  places:
    output: false
    permalink: /place/:path/
  guidelines:
    output: true
    permalink: /guidelines/:path/
  styleguide:
    output: true
    permalink: /styleguide/:path/

defaults:
  - scope:
      path: ""
      type: policies
    values:
      layout: policy
      comments: true
      sunlight: nil
  - scope:
      path: ""
      type: states
    values:
      layout: state
  - scope:
      path: ""
      type: places
    values:
      layout: default
      type: local
      no_text: false
      wwc: nil
  - scope:
      path: ""
      type: guidelines
    values:
      layout: guideline

frontmatter_tests:
  path: "tests/schema"

footer:
  image: /assets/img/logos/18F-Logo-M.png
  email:
  twitter:
    - 18f
    - usgsa
  text: This site was built using <a href="https://federalist.18f.gov/" target="_blank">Federalist, from 18F</a>. # Change to a tag line for your agency

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
- .about.yml
- .cfignore
- .codeclimate.yml
- .gitignore
- .gitmodules
- .hound.yml
- api-endpoints
- bin
- build
- circle.yml
- config_blog.rb
- CONTRIBUTING.md
- docker-compose.yml
- docker_entrypoint.rb
- Dockerfile
- examples/
- Gemfile*
- ISSUE_TEMPLATE.md
- killport
- LICENSE.md
- node_modules
- package.json
- pages/our-work.html
- PULL_REQUEST_TEMPLATE.md
- README.md
- spec/
- system-security-plan.yml
- tests/
- tests/schema/tags.yml
- tmp/
- vendor

# jekyll plugins
# gems:
#   - jekyll-sitemap
#   - jekyll-archives
#   - jekyll-redirect-from
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-paginate
gems:
  - 'jekyll-redirect-from'

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
